package server

import (
	"database/sql"
	_ "github.com/lib/pq"
	httpSwagger "github.com/swaggo/http-swagger"

	"fmt"
	"log"
	"net/http"

	_ "github.com/Arash-mlk24/simple-task-manager-web-backend/docs" // docs generated by swag
	"github.com/gorilla/mux"
)

func Config() {
	db, err := sql.Open("postgres", "postgres://postgres:T@skM@nagerP@stgresDb@127.0.0.1:5432/postgres?sslmode=disable")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	router := mux.NewRouter()
	RegisterRoutes(router, db)

	// Swagger route
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	fmt.Println("Server running at http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", router))
}
