package server

import (
	"github.com/Arash-mlk24/simple-task-manager-web-backend/internal/infrastructure/db"
	_ "github.com/lib/pq"
	httpSwagger "github.com/swaggo/http-swagger"

	"fmt"
	"log"
	"net/http"

	_ "github.com/Arash-mlk24/simple-task-manager-web-backend/docs" // docs generated by swag
	"github.com/gorilla/mux"
)

func Config() {
	database := db.Config() // connects and auto-migrates

	router := mux.NewRouter()
	RegisterRoutes(router, database)

	// Swagger route
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	fmt.Println("Server running at http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", router))
}
