basePath: /
definitions:
  dto.UserResponse:
    properties:
      email:
        example: arash.mros@gmail.com
        type: string
      id:
        example: 1
        type: integer
      username:
        example: Arash_mlk24
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server using Go's default net/http
  title: Swagger Example API (net/http)
  version: "1.0"
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.UserResponse'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user
      tags:
      - users
swagger: "2.0"
